// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { BaseService } from '../base-service';
import { ContentType, HttpResponse } from '../../http';
import { RequestConfig } from '../../http/types';
import {
  PagedResultOfAllLoyaltyBarClaimModel,
  PagedResultOfAvailableLoyaltyBarClaimModel,
  RedeemedLoyaltyBarClaimModel,
  pagedResultOfAllLoyaltyBarClaimModelResponse,
  pagedResultOfAvailableLoyaltyBarClaimModelResponse,
  redeemedLoyaltyBarClaimModelResponse,
} from '../common';
import {
  PosOfferGetAllPosOffersForContactParams,
  PosOfferGetAvailablePosOffersForContactParams,
} from './request-params';

export class PosoffersService extends BaseService {
  /**
 * Get all POS offers for a contact. Expired, redeemed and available.

Finds the contact by using a key value other than Contact Id. This can
only be used for contact types with exactly ONE key.
The contact key attribute is configured for each Voyado instance.
 * @param {string} keyValue - Key value, e.g. ssn, externalId, memberNumber, phone number etc.
 * @returns {Promise<HttpResponse<PagedResultOfAllLoyaltyBarClaimModel>>} OK
 */
  async posOfferGetAllPosOffersByKey(
    keyValue: string,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<PagedResultOfAllLoyaltyBarClaimModel>> {
    const path = this.client.buildPath('/api/v2/contacts/bykey/{keyValue}/posoffers/all', { keyValue: keyValue });
    const options: any = {
      responseSchema: pagedResultOfAllLoyaltyBarClaimModelResponse,
      requestSchema: z.any(),
      headers: {},
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      retry: requestConfig?.retry,
      config: this.config,
    };
    return this.client.get(path, options);
  }

  /**
 * Get all available POS offers for a contact. 
Expired and redeemed offers are excluded.

Finds the contact by using a key value other than Contact Id. This can
only be used for contact types with exactly ONE key.
The contact key attribute is configured for each Voyado instance.
 * @param {string} keyValue - Key value, e.g. ssn, externalId, memberNumber, phone number etc.
 * @returns {Promise<HttpResponse<PagedResultOfAvailableLoyaltyBarClaimModel>>} OK
 */
  async posOfferGetAvailablePosOffersByKey(
    keyValue: string,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<PagedResultOfAvailableLoyaltyBarClaimModel>> {
    const path = this.client.buildPath('/api/v2/contacts/bykey/{keyValue}/posoffers/available', { keyValue: keyValue });
    const options: any = {
      responseSchema: pagedResultOfAvailableLoyaltyBarClaimModelResponse,
      requestSchema: z.any(),
      headers: {},
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      retry: requestConfig?.retry,
      config: this.config,
    };
    return this.client.get(path, options);
  }

  /**
 * Get all POS offers for a contact. Expired, redeemed and available.

Finds the contact by using a key value other than Contact Id. This can
only be used for contact types with exactly ONE key.
The contact key attribute is configured for each Voyado instance.
 * @param {string} keyValue - Key value, e.g. ssn, externalId, memberNumber, phone number etc.
 * @param {string} contactType - Contact type, e.g. "member".
 * @returns {Promise<HttpResponse<PagedResultOfAllLoyaltyBarClaimModel>>} OK
 */
  async posOfferGetAllPosOffersByContactTypeAndKey(
    keyValue: string,
    contactType: string,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<PagedResultOfAllLoyaltyBarClaimModel>> {
    const path = this.client.buildPath('/api/v2/contacts/{contactType}/bykey/{keyValue}/posoffers/all', {
      keyValue: keyValue,
      contactType: contactType,
    });
    const options: any = {
      responseSchema: pagedResultOfAllLoyaltyBarClaimModelResponse,
      requestSchema: z.any(),
      headers: {},
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      retry: requestConfig?.retry,
      config: this.config,
    };
    return this.client.get(path, options);
  }

  /**
 * Get all available POS offers for a contact. 
Expired and redeemed offers are excluded.

Finds the contact by using a key value other than Contact Id. This can
only be used for contact types with exactly ONE key.
The contact key attribute is configured for each Voyado instance.
 * @param {string} keyValue - Key value, e.g. ssn, externalId, memberNumber, phone number etc.
 * @param {string} contactType - Contact type, e.g. "member".
 * @returns {Promise<HttpResponse<PagedResultOfAvailableLoyaltyBarClaimModel>>} OK
 */
  async posOfferGetAvailablePosOffersByContactTypeAndKey(
    keyValue: string,
    contactType: string,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<PagedResultOfAvailableLoyaltyBarClaimModel>> {
    const path = this.client.buildPath('/api/v2/contacts/{contactType}/bykey/{keyValue}/posoffers/available', {
      keyValue: keyValue,
      contactType: contactType,
    });
    const options: any = {
      responseSchema: pagedResultOfAvailableLoyaltyBarClaimModelResponse,
      requestSchema: z.any(),
      headers: {},
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      retry: requestConfig?.retry,
      config: this.config,
    };
    return this.client.get(path, options);
  }

  /**
 * Get all POS offers for a contact. Expired, redeemed and available.
The result can be paginated, using the offset and
count query parameters.
Note: *expiresOn* is obsolete and is always **null**
 * @param {string} contactId - Contact identifier (GUID).
 * @param {number} [offset] - The first item to retrieve. (Default value 0)
 * @param {number} [count] - The max number of items to retrieve. (Default value 100)
 * @returns {Promise<HttpResponse<PagedResultOfAllLoyaltyBarClaimModel>>} OK
 */
  async posOfferGetAllPosOffersForContact(
    contactId: string,
    params?: PosOfferGetAllPosOffersForContactParams,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<PagedResultOfAllLoyaltyBarClaimModel>> {
    const path = this.client.buildPath('/api/v2/contacts/{contactId}/posoffers/all', { contactId: contactId });
    const options: any = {
      responseSchema: pagedResultOfAllLoyaltyBarClaimModelResponse,
      requestSchema: z.any(),
      queryParams: {},
      headers: {},
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      retry: requestConfig?.retry,
      config: this.config,
    };
    if (params?.offset) {
      options.queryParams['offset'] = params?.offset;
    }
    if (params?.count) {
      options.queryParams['count'] = params?.count;
    }
    return this.client.get(path, options);
  }

  /**
 * Get all available POS offers for a contact. 
Expired and redeemed offers are excluded.

The result can be paginated, using the offset and
count query parameters.
 * @param {string} contactId - Contact identifier (GUID).
 * @param {number} [offset] - The first item to retrieve. (Default value 0)
 * @param {number} [count] - The max number of items to retrieve. (Default value 100)
 * @returns {Promise<HttpResponse<PagedResultOfAvailableLoyaltyBarClaimModel>>} OK
 */
  async posOfferGetAvailablePosOffersForContact(
    contactId: string,
    params?: PosOfferGetAvailablePosOffersForContactParams,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<PagedResultOfAvailableLoyaltyBarClaimModel>> {
    const path = this.client.buildPath('/api/v2/contacts/{contactId}/posoffers/available', { contactId: contactId });
    const options: any = {
      responseSchema: pagedResultOfAvailableLoyaltyBarClaimModelResponse,
      requestSchema: z.any(),
      queryParams: {},
      headers: {},
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      retry: requestConfig?.retry,
      config: this.config,
    };
    if (params?.offset) {
      options.queryParams['offset'] = params?.offset;
    }
    if (params?.count) {
      options.queryParams['count'] = params?.count;
    }
    return this.client.get(path, options);
  }

  /**
   * Redeems a POS offer for a Contact using the internal Contact Id
   * @param {string} id - The id returned from the get operation (GUID)
   * @param {string} contactId - Contact identifier (GUID).
   * @returns {Promise<HttpResponse<RedeemedLoyaltyBarClaimModel>>} OK
   */
  async posOfferRedeem(
    id: string,
    contactId: string,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<RedeemedLoyaltyBarClaimModel>> {
    const path = this.client.buildPath('/api/v2/contacts/{contactId}/posoffers/{id}/redeem', {
      id: id,
      contactId: contactId,
    });
    const options: any = {
      responseSchema: redeemedLoyaltyBarClaimModelResponse,
      requestSchema: z.any(),
      headers: {},
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      retry: requestConfig?.retry,
      config: this.config,
    };
    return this.client.post(path, options);
  }

  /**
 * Redeems a POS offer for a Contact using the key for the contact type

Finds the contact by using a key value other than Contact Id. This can
only be used for contact types with exactly ONE key.
The contact key attribute is configured for each Voyado instance.
 * @param {string} id - The id returned from the get operation (GUID)
 * @param {string} keyValue - Key value, e.g. ssn, externalId, memberNumber, phone number etc.
 * @returns {Promise<HttpResponse<RedeemedLoyaltyBarClaimModel>>} OK
 */
  async posOfferRedeemByKey(
    id: string,
    keyValue: string,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<RedeemedLoyaltyBarClaimModel>> {
    const path = this.client.buildPath('/api/v2/contacts/bykey/{keyValue}/posoffers/{id}/redeem', {
      id: id,
      keyValue: keyValue,
    });
    const options: any = {
      responseSchema: redeemedLoyaltyBarClaimModelResponse,
      requestSchema: z.any(),
      headers: {},
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      retry: requestConfig?.retry,
      config: this.config,
    };
    return this.client.post(path, options);
  }

  /**
 * Redeems a POS offer for a Contact using the key for the contact type

Finds the contact by using a key value other than Contact Id. This can
only be used for contact types with exactly ONE key.
The contact key attribute is configured for each Voyado instance.
 * @param {string} id - The id returned from the get operation (GUID)
 * @param {string} keyValue - Key value, e.g. ssn, externalId, memberNumber, phone number etc.
 * @param {string} contactType - Contact type, e.g. "member" or "contact".
 * @returns {Promise<HttpResponse<RedeemedLoyaltyBarClaimModel>>} OK
 */
  async posOfferRedeemByContactTypeAndKey(
    id: string,
    keyValue: string,
    contactType: string,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<RedeemedLoyaltyBarClaimModel>> {
    const path = this.client.buildPath('/api/v2/contacts/{contactType}/bykey/{keyValue}/posoffers/{id}/redeem', {
      id: id,
      keyValue: keyValue,
      contactType: contactType,
    });
    const options: any = {
      responseSchema: redeemedLoyaltyBarClaimModelResponse,
      requestSchema: z.any(),
      headers: {},
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      retry: requestConfig?.retry,
      config: this.config,
    };
    return this.client.post(path, options);
  }
}
