// This file was generated by liblab | https://liblab.com/

export interface PosOfferGetAllPosOffersForContactParams {
  offset?: number;
  count?: number;
}

export interface PosOfferGetAvailablePosOffersForContactParams {
  offset?: number;
  count?: number;
}
