// This file was generated by liblab | https://liblab.com/

export interface StoresVGetStoresParams {
  includeInactive?: boolean;
}

export interface StoresVGetStoreParams {
  includeInactive?: boolean;
}
