// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const apiPromotionRedemptionChannelModelType = z.enum(['POS', 'ECOM', 'OTHER']);

export type ApiPromotionRedemptionChannelModelType = z.infer<typeof apiPromotionRedemptionChannelModelType>;
