// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const apiPromotionRedemptionChannelModelValueType = z.enum([
  'PERCENT',
  'MONEY',
  'EXTERNALOFFER',
  'MANUAL',
  'SWIPE',
]);

export type ApiPromotionRedemptionChannelModelValueType = z.infer<typeof apiPromotionRedemptionChannelModelValueType>;
