// This file was generated by liblab | https://liblab.com/

export interface MultichannelPromotionsGetByExternalIdParams {
  externalId: string;
}

export interface MultichannelPromotionsDeleteByExternalIdParams {
  externalId: string;
}

export interface MultichannelPromotionsGetByValidityExternalIdParams {
  externalId: string;
}
