// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { BaseService } from '../base-service';
import { ContentType, HttpResponse } from '../../http';
import { RequestConfig } from '../../http/types';
import { ApiConsentDefinition, apiConsentDefinitionResponse } from '../common';

export class ConsentsService extends BaseService {
  /**
 * Get all consents definitions

Example of metaData for a Consent:

"metaData": {
  "conditionText": {
    "sv-SE": "Svensk villkorstext",
    "en-GB": "English text to show for condition"
  },
  "displayText": {
    "sv-SE": "Svensk text att visa",
    "en-GB": "English text to display"
  },
  "linkText": {
    "sv-SE": "Svensk text att visa på länk",
    "en-GB": "English text to show on link"
  }
}
 * @returns {Promise<HttpResponse<ApiConsentDefinition[]>>} OK
 */
  async consentsGetConsents(requestConfig?: RequestConfig): Promise<HttpResponse<ApiConsentDefinition[]>> {
    const path = '/api/v2/consents';
    const options: any = {
      responseSchema: z.array(apiConsentDefinitionResponse),
      requestSchema: z.any(),
      headers: {},
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      retry: requestConfig?.retry,
      config: this.config,
    };
    return this.client.get(path, options);
  }
}
