// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { BaseService } from '../base-service';
import { ContentType, HttpResponse } from '../../http';
import { RequestConfig } from '../../http/types';
import { MemberStatusModel, memberStatusModelResponse } from '../common';
import { MemberStatusVGetParams } from './request-params';

export class MemberstatusService extends BaseService {
  /**
 * Gets the first found member that matches the query.

Operation to get member overview. Is usually called from 
POS after a member gives some identification information
this method returns the status together with contactId (GUID)
and memberNumber (if available). The contactId may be used
to get detailed contact information. 

Common identification fields that may be used in the query: 
socialSecurityNumber, email, mobilePhone, memberNumber and externalId

The language of the returned answer is controlled by the language setting of the user connected to the API-key.
 * @param {string} query - {fieldId}:{value}, e.g. email:test@test.com
 * @returns {Promise<HttpResponse<MemberStatusModel>>} OK
 */
  async memberStatusVGet(
    params: MemberStatusVGetParams,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<MemberStatusModel>> {
    const path = '/api/v2/memberstatus';
    const options: any = {
      responseSchema: memberStatusModelResponse,
      requestSchema: z.any(),
      queryParams: {},
      headers: {},
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      retry: requestConfig?.retry,
      config: this.config,
    };
    if (params?.query) {
      options.queryParams['query'] = params?.query;
    }
    return this.client.get(path, options);
  }
}
