// This file was generated by liblab | https://liblab.com/

import {
  ChallengeGetChallengeDefinitionsStatus,
  ChallengeGetChallengesFilter,
  challengeGetChallengeDefinitionsStatus,
  challengeGetChallengesFilter,
} from './models';

export interface ChallengeGetChallengeDefinitionsParams {
  offset?: number;
  count?: number;
  status?: ChallengeGetChallengeDefinitionsStatus;
}

export interface ChallengeGetChallengesParams {
  contactId: string;
  definitionId?: string;
  offset?: number;
  count?: number;
  filter?: ChallengeGetChallengesFilter;
}

export interface ChallengeConsentParams {
  contactId: string;
}
