// This file was generated by liblab | https://liblab.com/

import { VoyadoEngage } from 'voyado_engage';

(async () => {
  const voyadoEngage = new VoyadoEngage({
    token: 'YOUR_TOKEN',
  });

  const { data } = await voyadoEngage.achievements.achievementsGetAllAchievements({
    offset: 7,
    count: 10,
  });

  console.log(data);
})();
