// This file was generated by liblab | https://liblab.com/

export interface BonusChecksGetBonusChecksForContactParams {
  offset?: number;
  count?: number;
}

export interface BonusChecksGetRedeemedBonusChecksForContactParams {
  offset?: number;
  count?: number;
}

export interface BonusChecksGetAvailableBonusChecksParams {
  offset?: number;
  count?: number;
}
