// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const bonusPointTransactionModelType = z.enum([
  'Purchase',
  'Adjustment',
  'Recruitment',
  'PurchaseReduction',
  'Return',
  'BonusCheck',
  'DueDate',
  'StartBonus',
  'BonusPromotion',
  'BonusPromotionReturn',
  'FromAutomation',
  'BonusBalanceAdjustment',
  'PurchaseWithPoints',
]);

export type BonusPointTransactionModelType = z.infer<typeof bonusPointTransactionModelType>;
