// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const changeType = z.enum(['Created', 'Updated', 'Deleted']);

export type ChangeType = z.infer<typeof changeType>;
