// This file was generated by liblab | https://liblab.com/

export interface ContactOverviewGetContactOverviewAsyncParams {
  contactType?: string;
  contactId?: string;
  email?: string;
  socialSecurityNumber?: string;
  mobilePhone?: string;
  customKey?: string;
  any_?: string;
}
