// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { BaseService } from '../base-service';
import { ContentType, HttpResponse } from '../../http';
import { RequestConfig } from '../../http/types';
import { IdName, idNameResponse } from '../common';

export class TargetAudiencesService extends BaseService {
  /**
   *
   * @returns {Promise<HttpResponse<IdName[]>>} List of all target audiences
   */
  async targetAudienceGetTargetAudiences(requestConfig?: RequestConfig): Promise<HttpResponse<IdName[]>> {
    const path = '/api/v2/target-audiences';
    const options: any = {
      responseSchema: z.array(idNameResponse),
      requestSchema: z.any(),
      headers: {},
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      retry: requestConfig?.retry,
      config: this.config,
    };
    return this.client.get(path, options);
  }
}
