// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { BaseService } from '../base-service';
import { ContentType, HttpResponse } from '../../http';
import { RequestConfig } from '../../http/types';
import { EnrichmentVariableGroup, enrichmentVariableGroupResponse } from '../common';

export class BisnodeService extends BaseService {
  /**
   *
   * @param {string} contactId - Contact identifier
   * @returns {Promise<HttpResponse<EnrichmentVariableGroup[]>>} OK
   */
  async bisnodeVGetEnrichments(
    contactId: string,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<EnrichmentVariableGroup[]>> {
    const path = this.client.buildPath('/api/v2/bisnode/{contactId}/enrichments', { contactId: contactId });
    const options: any = {
      responseSchema: z.array(enrichmentVariableGroupResponse),
      requestSchema: z.any(),
      headers: {},
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      retry: requestConfig?.retry,
      config: this.config,
    };
    return this.client.get(path, options);
  }
}
